### ISSUE TITLE
Error Unknown column - Repo.preload

### ISSUE THREAD

**Issue by gilbertojuniortelgo** [Excipients/rummage_phoenix#21]
I have currently inserted the following line in my index.html

<%= search_form(@conn, @rummage, [fields:
        [ city: %{label: "Search City", search_type: "like"}], button_class: "btn"]) %>

But it returns an error
Error: 
(1054): Unknown column 'd0.city' in 'where clause'
How can I solve this problem?
Note:
I use, |> Repo.preload(:city) to recognize "id" in "name"

Model 1>

```
defmodule Relat.Disp do
  use Relat.Web, :model
          use Ecto.Schema
          use Rummage.Ecto


  schema "disps" do
    field :disponib, :float
    field :date, Ecto.Date
    belongs_to :city, Relat.Local

    timestamps()
  end

  @doc """
  Builds a changeset based on the `struct` and `params`.
  """
  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:disponib, :date, :city_id])
    |> validate_required([:disponib, :date, :city_id])
  end
end
```

Model 2 >

```
defmodule Relat.Local do
  use Relat.Web, :model

  schema "locais" do
    field :city, :string

    timestamps()
  end

  @doc """
  Builds a changeset based on the `struct` and `params`.
  """
  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:city])
    |> validate_required([:city])
  end
end
```

**Comment by aditya7iyengar** [comment]
I'm assuming you're on the index of `disp` and are trying to search by `local.city`. This is associations search. I haven't written a blog about it yet, but you can add `assoc` keyto your `search_form`. Your function should look somewhat like this:

```elixir
<%= search_form(@conn, @rummage, [fields:
  [
    city: %{label: "Search City", search_type: "like",  assoc: ["city"]}, 
    button_class: "btn"
  ]) %>
```

**Comment by gilbertojuniortelgo** [comment]
It worked perfectly.
Thank you
